from enum import StrEnum


class MarketCandleDirection(StrEnum):
    CLOSE_ABOVE_OPEN = "CLOSE_ABOVE_OPEN"
    CLOSE_BELOW_OPEN = "CLOSE_BELOW_OPEN"
    CLOSE_EQUAL_OPEN = "CLOSE_EQUAL_OPEN"


class BasicTrend(StrEnum):
    RISING_STRUCTURE = "RISING_STRUCTURE"
    FALLING_STRUCTURE = "FALLING_STRUCTURE"
    MIXED_STRUCTURE = "MIXED_STRUCTURE"
